services:
  subclassestracker-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports: 
      - "18888:18888"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${DEFAULTUSER}"
      POSTGRES_PASSWORD: "${DEFAULTPASS}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "subclassestracker.aspirehost-f4fa103c1e-postgres-data"
        read_only: false
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__ParquetCache: "${CONNSTRING}"
      ConnectionStrings__DefaultDbConn: "${DEFAULTCONNSTRING}"
      CachingSettings__CacheRootPath: "/var/lib/subclasses/parquet/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://subclassestracker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "127.0.0.1:7192:${API_PORT}"
    expose:
      - "${API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
    restart: "always"
  cleaner:
    image: "${CLEANER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__ParquetCache: "${CONNSTRING}"
      CachingSettings__CacheRootPath: "/var/lib/subclasses/parquet/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://subclassestracker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "cleaner"
    depends_on:
      postgres:
        condition: "service_started"
      api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  subclassestracker.aspirehost-f4fa103c1e-postgres-data:
    driver: "local"
